version: '3.8'

x-env-file: &services-env-file
  env_file:
    - ./.env

services:
  auth_db:
    container_name: auth_db
    build:
      context: .
      dockerfile: ./migrations/Dockerfile
    volumes:
      - postgres_data:/var/lib/postgresql/data
    <<: *services-env-file
    ports:
      - "${POSTGRES_PORT}:${POSTGRES_CONTAINER_PORT}"
    networks:
      - backend
    restart: always

  auth_redis:
    image: redis:7.0.9
    container_name: auth_redis
    ports:
      - "${REDIS_PORT}:${REDIS_CONTAINER_PORT}"
    networks:
      - backend

  auth_app:
    container_name: auth_app
    build:
      context: ./src
      dockerfile: Dockerfile
    <<: *services-env-file
    ports:
      - "${AUTH_PORT}:${AUTH_CONTAINER_PORT}"
    networks:
      - backend
    restart: always

  auth_swagger:
    image: swaggerapi/swagger-ui
    container_name: auth_swagger
    ports:
      - "8080:8080"
    volumes:
      - ./design:/usr/share/nginx/html/doc
    environment:
      API_URL: doc/openapi.yaml
    depends_on:
      - auth_app
    profiles:
      - testing

volumes:
  postgres_data:

networks:
  backend:
    name: backend
    driver: bridge
