"""Create initial tables

Revision ID: 6a6f5318432d
Revises:
Create Date: 2023-04-09 12:08:24.766710

"""
import sqlalchemy as sa

from alembic import op
from sqlalchemy import FetchedValue

# revision identifiers, used by Alembic.
revision = '6a6f5318432d'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # Create schema "content" if it doesn't exist
    op.execute('CREATE SCHEMA IF NOT EXISTS content;')
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        'roles',
        sa.Column('name', sa.String(length=50), nullable=True),
        sa.Column('description', sa.String(length=255), nullable=True),
        sa.Column('id', sa.UUID(), nullable=False),
        sa.Column('created_at', sa.DateTime(), nullable=True),
        sa.Column('updated_at', sa.DateTime(), nullable=True),
        sa.PrimaryKeyConstraint('id'),
        sa.UniqueConstraint('id'),
        sa.UniqueConstraint('name'),
        schema='content',
    )
    op.create_table(
        'users',
        sa.Column('username', sa.String(length=50), nullable=False),
        sa.Column('email', sa.String(length=50), nullable=True),
        sa.Column('fs_uniquifier', sa.String(length=255), nullable=False),
        sa.Column('password', sa.String(length=255), nullable=False),
        sa.Column('active', sa.Boolean(), nullable=False),
        sa.Column('is_totp_enabled', sa.Boolean(), nullable=False),
        sa.Column('two_factor_secret', sa.String(length=255), nullable=True),
        sa.Column('id', sa.UUID(), nullable=False),
        sa.Column('created_at', sa.DateTime(), nullable=True),
        sa.Column('updated_at', sa.DateTime(), nullable=True),
        sa.PrimaryKeyConstraint('id'),
        sa.UniqueConstraint('email'),
        sa.UniqueConstraint('fs_uniquifier'),
        sa.UniqueConstraint('id'),
        sa.UniqueConstraint('username'),
        schema='content',
    )
    op.create_table(
        'auth_history',
        sa.Column('user_id', sa.UUID(), nullable=True),
        sa.Column('ip_address', sa.String(length=50), nullable=False),
        sa.Column('user_agent', sa.String(length=255), nullable=False),
        sa.Column('is_successful', sa.Boolean(), nullable=False),
        sa.Column('device', sa.String(length=255), nullable=True),
        sa.Column('auth_event_type', sa.String(), nullable=False),
        sa.Column(
            'auth_event_time',
            sa.DateTime(timezone=True),
            server_default=sa.text('now()'),
            nullable=True,
        ),
        sa.Column('auth_event_fingerprint', sa.String(), nullable=False),
        sa.Column('id', sa.UUID(), nullable=False),
        sa.Column('created_at', sa.DateTime(), nullable=True),
        sa.Column('updated_at', sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(['user_id'], ['content.users.id'], ondelete='CASCADE'),
        sa.PrimaryKeyConstraint('id'),
        sa.UniqueConstraint('id'),
        schema='content',
    )
    op.create_table(
        'social_accounts',
        sa.Column('user_id', sa.UUID(), nullable=True),
        sa.Column('social_id', sa.String(length=255), nullable=False),
        sa.Column('social_provider_name', sa.String(length=50), nullable=False),
        sa.Column('id', sa.UUID(), nullable=False),
        sa.ForeignKeyConstraint(['user_id'], ['content.users.id'], ondelete='CASCADE'),
        sa.PrimaryKeyConstraint('id'),
        sa.UniqueConstraint('id'),
        schema='content',
    )
    op.create_table(
        'tokens',
        sa.Column('token_owner_id', sa.UUID(), nullable=False),
        sa.Column('token_value', sa.String(), nullable=False),
        sa.Column('token_used', sa.Boolean(), nullable=True),
        sa.Column(
            'created_at',
            sa.DateTime(timezone=True),
            server_default=sa.text('now()'),
            nullable=True,
        ),
        sa.Column(
            'expires_at',
            sa.DateTime(timezone=True),
            server_default=FetchedValue(),
            nullable=False,
        ),
        sa.Column('id', sa.UUID(), nullable=False),
        sa.ForeignKeyConstraint(
            ['token_owner_id'],
            ['content.users.id'],
        ),
        sa.PrimaryKeyConstraint('id'),
        sa.UniqueConstraint('id'),
        schema='content',
    )
    op.create_table(
        'user_roles',
        sa.Column('user_id', sa.UUID(), nullable=True),
        sa.Column('role_id', sa.UUID(), nullable=True),
        sa.Column('id', sa.UUID(), nullable=False),
        sa.ForeignKeyConstraint(['role_id'], ['content.roles.id'], ondelete='CASCADE'),
        sa.ForeignKeyConstraint(['user_id'], ['content.users.id'], ondelete='CASCADE'),
        sa.PrimaryKeyConstraint('id'),
        sa.UniqueConstraint('id'),
        schema='content',
    )
    # ### end Alembic commands ###


def downgrade():
    # Drop schema "content" if it exists
    op.execute('DROP SCHEMA IF EXISTS content CASCADE;')
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user_roles', schema='content')
    op.drop_table('tokens', schema='content')
    op.drop_table('social_accounts', schema='content')
    op.drop_table('auth_history', schema='content')
    op.drop_table('users', schema='content')
    op.drop_table('roles', schema='content')
    # ### end Alembic commands ###
